---
- name: "Where am i"
  become: yes
  shell: |
    pwd
    ls -al

- name: "Copy tarball"
  become: yes
  shell: |
    cp /root/project/artifact.tar.gz ~ 

- name: "Extract tarball"
  become: yes
  shell: |
    cd 
    pwd
    tar -xvzf artifact.tar.gz
    ls -al

- name: "Start application"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
