---
- name: "Copy tarball"
  ansible.builtin.copy:
    src: /root/project/artifact.tar.gz 
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: "Extract tarball"
  become: yes
  shell: |
    cd /home/ubuntu
    tar -xvf artifact.tar.gz

- name: "Start application"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
